# -*- coding: utf-8 -*-
"""embedding_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17N5hf0AprT1AkhTpkLO6x359aw1ayYTk
"""

import torch
from torch.utils.data import DataLoader
import config2 as config
import importlib
import sys




def extract_and_save_embeddings(dataset, model, save_path=None):
    """Extracts embeddings using the specified DINOv2 model and saves them."""
    device = config.args.device
    model.to(device)

    if save_path is None:
        save_path = config.args.embedding_save_path  # Default to config file path

    dataloader = DataLoader(dataset, batch_size=config.args.batch_size, shuffle=False)
    all_embeddings, all_labels = [], []

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            embeddings = model(inputs)  # Forward pass through ViT model
            all_embeddings.append(embeddings.cpu())
            all_labels.append(labels.cpu())

    final_embeddings = torch.cat(all_embeddings, dim=0)
    final_labels = torch.cat(all_labels, dim=0)

    torch.save((final_embeddings, final_labels), save_path)
    print(f"✅ Embeddings saved to {save_path}")