# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgeY3Nor7FQiqQ1I6t7O-OTX6gC6fJh9
"""

import torch
import numpy as np
import random

def set_random_seed(seed=42):
    """Set seed for reproducibility."""
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def get_label_name(label_index):
    """Convert numerical label back to class name."""
    reverse_label_dict = {v: k for k, v in args.label_dict.items()}
    return reverse_label_dict.get(label_index, "Unknown")